### ISSUE TITLE
Getting in touch?

### ISSUE THREAD

**Issue by jayepoch** [mbortnyck/qfp#1]
Hey Michael!

I found your project after finding Reinhard & co's papers online. I work in the electronic music space (radio, music labels, distribution, etc) and am very interested in audio fingerprinting.

I didn't see a way to contact you on your git profile, so I thought I'd reach out here - would love to connect if you're up for it!

**Comment by mbortnyck** [comment]
Hello Jason,
My e-mail is michael.bortnyck@gmail.com
Cheers
