### ISSUE TITLE
Quad validation

### ISSUE THREAD

**Issue by 00001101-xt** [mbortnyck/qfp#9]
About the quad validation condition(function `_valid_quad`)
```python
def _valid_quad(q):
    """
    Evaluates:
          Ay < By
      Ax < Cx <= Dx <= Bx
      Ay < Cy ,  Dy <= By
    !! NOTE: assumes combinations are sorted by x value
    (default behavior of itertools.combinations)
    """
    if q.A.y < q.C.y < q.B.y and q.A.y < q.D.y <= q.B.y:
        return True
    else:
        return False
```

why not `q.A.y < q.C.y <= q.B.y` ?

**Comment by mbortnyck** [comment]
Probably just an oversight. Test it out and submit a pull request (as long as the quad rules are consistent between the reference and query I don't see this changing anything).
